name: Build
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Install Packer 1.6.1
        run: |
          wget -q -O packer.zip https://releases.hashicorp.com/packer/1.6.1/packer_1.6.1_linux_amd64.zip
          unzip packer.zip
          sudo install packer /usr/bin/packer
          packer version

      - name: Checkout code
        uses: actions/checkout@v2
